// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:8920198f-1aeb-42db-8608-c0324fb8d4e4',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'weatherapp-hosting-mobilehub-1356404945',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3d9lnfawvl1pd.cloudfront.net',
    'aws_mobile_analytics_app_id': 'ebcb8360b10f4b479dac9503dfc4c47d',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1b2085a1-520b-4f41-9094-5c6c67f670ff',
    'aws_project_name': 'weatherApp',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'weatherapp-mobilehub-1356404945',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_fTaEHBLSG',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '56nb197vnncu0edur7fjd9ptqs',
}

export default awsmobile;
